<a href="https://colab.research.google.com/github/sangeerthP-10/my_works/blob/main/MachineLearning/machine_learning(day2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression using Multiple Variables

In [58]:
import pandas as pd
from sklearn import linear_model

In [59]:
df=pd.DataFrame({
    'area':[2600,3000,3200,3600,4000],
    'bedrooms':[3,4,None,3,5],
    'age':[20,14,18,30,8],
    'price':[550000,565000,610000,595000,760000]
})
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   14  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [60]:
import math
median=math.floor(df.bedrooms.median())
median

3

In [61]:
df.bedrooms.fillna(median,inplace=True)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   14  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [62]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   14  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [63]:
reg=linear_model.LinearRegression()

In [64]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [65]:
reg.predict([[2000,3,20]])

array([439738.98858075])

Exercise(Hiring data Prediction)

In [66]:
hiring_df=pd.DataFrame({
    'experience':[None,None,'five','two','seven','three','ten','eleven'],
    'test_score':[8,8,6,10,9,7,None,7],
    'interview_score':[9,6,7,10,6,10,7,8],
    'salary':[50000,45000,60000,65000,70000,62000,72000,80000]
})
hiring_df

  experience  test_score  interview_score  salary
0       None         8.0                9   50000
1       None         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [67]:
import pandas as pd
import numpy as np



# Define the mapping dictionary
word_to_num_map = {
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six':6,
    'nine':9,
    'seven':7,
    'eleven':11,
    'ten': 10
}

# Use the map function to convert the column
hiring_df['experience_numeric'] = hiring_df['experience'].map(word_to_num_map)

# Print the result and data types to verify
print(hiring_df)

  experience  test_score  interview_score  salary  experience_numeric
0       None         8.0                9   50000                 NaN
1       None         8.0                6   45000                 NaN
2       five         6.0                7   60000                 5.0
3        two        10.0               10   65000                 2.0
4      seven         9.0                6   70000                 7.0
5      three         7.0               10   62000                 3.0
6        ten         NaN                7   72000                10.0
7     eleven         7.0                8   80000                11.0

In [68]:
hiring_df.drop('experience',axis=1,inplace=True)

In [69]:
hiring_df

   test_score  interview_score  salary  experience_numeric
0         8.0                9   50000                 NaN
1         8.0                6   45000                 NaN
2         6.0                7   60000                 5.0
3        10.0               10   65000                 2.0
4         9.0                6   70000                 7.0
5         7.0               10   62000                 3.0
6         NaN                7   72000                10.0
7         7.0                8   80000                11.0

In [70]:
test_score_median=hiring_df['test_score'].median()
hiring_df['test_score'].fillna(test_score_median,inplace=True)
hiring_df.fillna(0,inplace=True)

In [71]:

model = linear_model.LinearRegression()

model.fit(hiring_df[['test_score','interview_score','experience_numeric']], hiring_df.salary)

LinearRegression()

**Question1: Predict Salary of candidate who has 2 years of experience,9 test_score, 6 interview_score**

In [72]:
import warnings
warnings.filterwarnings("ignore")

In [73]:
prediction=model.predict([[9,6,2]])
print(prediction)

[53205.96797671]

**Question 2 : Predict Salary of candidate who has 12 years of experience,10 test_score, 10 interview_score**

In [74]:
model.predict([[10,10,12]])

array([92002.18340611])