<a href="https://colab.research.google.com/github/sangeerthP-10/my_works/blob/main/pandas(day_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
india_weather =pd.DataFrame({
    "city":["mumbai","Delhi","Bangalore"],
    "temperature":[24,25,26],
    "humidity":[80,60,70]}
)

In [7]:
india_weather

        city  temperature  humidity
0     mumbai           24        80
1      Delhi           25        60
2  Bangalore           26        70

In [8]:
us_weather =pd.DataFrame({
    "city":["NewYork","chicago","orlando"],
    "temperature":[21,15,36],
    "humidity":[85,65,75]}
)
us_weather

      city  temperature  humidity
0  NewYork           21        85
1  chicago           15        65
2  orlando           36        75

In [13]:
df=pd.concat([india_weather,us_weather],ignore_index=True)

In [14]:
df

        city  temperature  humidity
0     mumbai           24        80
1      Delhi           25        60
2  Bangalore           26        70
3    NewYork           21        85
4    chicago           15        65
5    orlando           36        75

In [16]:
df=pd.concat([india_weather,us_weather],ignore_index=False)
df

        city  temperature  humidity
0     mumbai           24        80
1      Delhi           25        60
2  Bangalore           26        70
0    NewYork           21        85
1    chicago           15        65
2    orlando           36        75

In [20]:
df=pd.concat([india_weather,us_weather],keys=["india","us"])
df

              city  temperature  humidity
india 0     mumbai           24        80
      1      Delhi           25        60
      2  Bangalore           26        70
us    0    NewYork           21        85
      1    chicago           15        65
      2    orlando           36        75

In [21]:
df.loc["us"]

      city  temperature  humidity
0  NewYork           21        85
1  chicago           15        65
2  orlando           36        75

In [22]:
temperature_df=pd.DataFrame({
    "city":["mumbai","Delhi","Bangalore"],
    "temperature":[24,25,26],
})
temperature_df

        city  temperature
0     mumbai           24
1      Delhi           25
2  Bangalore           26

In [25]:
windspeed_df=pd.DataFrame({
    "city":["mumbai","Delhi","Bangalore"],
    "windspeed":[24,25,26],
})
windspeed_df

        city  windspeed
0     mumbai         24
1      Delhi         25
2  Bangalore         26

In [28]:
df1=pd.concat([windspeed_df,temperature_df],axis=1)
df1

        city  windspeed       city  temperature
0     mumbai         24     mumbai           24
1      Delhi         25      Delhi           25
2  Bangalore         26  Bangalore           26

In [29]:
s=pd.Series(["humid","dry","rain"],name="event")

In [30]:
df2=pd.concat([temperature_df,s],axis=1)
df2

        city  temperature  event
0     mumbai           24  humid
1      Delhi           25    dry
2  Bangalore           26   rain