<a href="https://colab.research.google.com/github/sangeerthP-10/my_works/blob/main/pandas(day3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [15]:

new_df=df.replace(-99999,np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [18]:
newd_df=df.replace([-99999,'0'],np.nan)
newd_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [21]:
new_df=df.replace({
    'temperature':-99999,
    'windspeed':-99999,
    'event':'0'
},np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [22]:
new_df=df.replace({
    'temperature':-99999,
    'windspeed':-99999,
    'event':'0'
},{
    'temperature':30,
    'windspeed':9,
    'event':'No event'

})
new_df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017           30          7     Sunny
2  1/3/2017           28          9      Snow
3  1/4/2017           30          7  No event
4  1/5/2017           32          9      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34          5  No event

In [33]:
new_df=df.replace({
    -99999:33,

    '0':'No event'
})
new_df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017           33          7     Sunny
2  1/3/2017           28         33      Snow
3  1/4/2017           33          7  No event
4  1/5/2017           32         33      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34          5  No event

In [34]:
new_df.loc[[1, 2], 'temperature'] = '34F'
new_df

/tmp/ipython-input-4059129580.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '34F' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  new_df.loc[[1, 2], 'temperature'] = '34F'

        day temperature  windspeed     event
0  1/1/2017          32          6      Rain
1  1/2/2017         34F          7     Sunny
2  1/3/2017         34F         33      Snow
3  1/4/2017          33          7  No event
4  1/5/2017          32         33      Rain
5  1/6/2017          31          2     Sunny
6  1/6/2017          34          5  No event

In [38]:
new_df.loc[[1,2],'windspeed']='4mph'
new_df

        day temperature windspeed     event
0  1/1/2017          32         6      Rain
1  1/2/2017         34F      4mph     Sunny
2  1/3/2017         34F      4mph      Snow
3  1/4/2017          33         7  No event
4  1/5/2017          32        33      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No event

In [39]:
new_dfs=new_df.replace('[A-Za-z]','',regex=True)
new_dfs

        day temperature windspeed event
0  1/1/2017          32         6
1  1/2/2017          34         4
2  1/3/2017          34         4
3  1/4/2017          33         7
4  1/5/2017          32        33
5  1/6/2017          31         2
6  1/6/2017          34         5

In [40]:
new_df=new_df.replace({
    'temperature':'[A-Za-z]',
    'windspeed':'[A-Za-z]'
},'',regex=True)
new_df

        day temperature windspeed     event
0  1/1/2017          32         6      Rain
1  1/2/2017          34         4     Sunny
2  1/3/2017          34         4      Snow
3  1/4/2017          33         7  No event
4  1/5/2017          32        33      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No event

In [43]:
df=pd.DataFrame({
    'score':['exceptional','average','poor','good'],
    'student':['rob','tob','mob','cob']
})
df

         score student
0  exceptional     rob
1      average     tob
2         poor     mob
3         good     cob

In [44]:
new_df=df.replace(['exceptional','average','good','poor'],[4,3,2,1])
new_df

/tmp/ipython-input-775475882.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df=df.replace(['exceptional','average','good','poor'],[4,3,2,1])

   score student
0      4     rob
1      3     tob
2      1     mob
3      2     cob

In [45]:
df=pd.read_csv('weather_by_cities.csv')
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [48]:
g=df.groupby('city')

In [49]:
for city,city_df in g:
  print(city)
  print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [50]:
g.max('temperature')

          temperature  windspeed
city
mumbai             92         15
new york           36         12
paris              54         20

In [53]:
g.mean('windspeed')

          temperature  windspeed
city
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [54]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0